Grading at 12/08/2023:19:06:04.667662
For commit ID 970be8697820b68790983dfd1097864b0cce578e
Grading at Fri Dec  8 02:04:22 PM EST 2023
Doing some basic checking for your submission

Step 1
Checking that cyoa-step1 compiles
rm -f *~ cyoa-step1 cyoa-step2 cyoa-step3 cyoa-step4 cyoa-step1.o cyoa-step2.o cyoa-step3.o cyoa-step4.o cyoa.o
g++    -c -o cyoa-step1.o cyoa-step1.cpp
g++ -std=gnu++11 -pedantic -Wall -Werror -ggdb3 -c cyoa.cpp
g++ -o cyoa-step1 cyoa-step1.o cyoa.o
rm cyoa.o cyoa-step1.o
The code compiled (good)
Executable cyoa-step1 exists (good)
------------------------------------
Now running YOUR tests for step 1
------------------------------------


1.1: Current test is ./cyoa-step1 story1 < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Declaration order incorrect

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


1.2: Current test is ./cyoa-step1 test/step3_test7 < /dev/null
-----------------------------
Your output looks good. Lets check valgrind
Valgrind was clean


1.3: Current test is ./cyoa-step1 story2 < /dev/null
-----------------------------
Your output looks good. Lets check valgrind
Valgrind was clean


1.4: Current test is ./cyoa-step1 brokenstory < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Fail to open story.txt file

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


1.5: Current test is ./cyoa-step1 story1 story2 < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Invalid input command

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


1.6: Current test is ./cyoa-step1  < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Invalid input command

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


1.7: Current test is ./cyoa-step1 test/NoDelimiter < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Invalid digits from story.txt for page 

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


1.8: Current test is ./cyoa-step1 test/no_story < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Fail to open story.txt file

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


1.9: Current test is ./cyoa-step1 test/pageDeclareOrder < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Declaration order incorrect

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


1.10: Current test is ./cyoa-step1 test/size_t_2 < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Invalid digits from story.txt for page 

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


1.11: Current test is ./cyoa-step1 test/typeOfPage < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Story page input format invalid
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


1.12: Current test is ./cyoa-step1 test/WLnoChoice < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Logic error when adding choice not to type 'N'

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


1.13: Current test is ./cyoa-step1 test/number < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Invalid digits from story.txt for page 

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


1.14: Current test is ./cyoa-step1 test/pageNum < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Invalid digits from story.txt for page 

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


1.15: Current test is ./cyoa-step1 test/story1 < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Fail to open story.txt file

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


1.16: Current test is ./cyoa-step1 test/filename < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Fail to open File
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


1.17: Current test is ./cyoa-step1 test/orderNum < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Page is not yet declared

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


1.18: Current test is ./cyoa-step1 test/size_t < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Out of range error

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


1.19: Current test is ./cyoa-step1 story3 < /dev/null
-----------------------------
Your output looks good. Lets check valgrind
Valgrind was clean


1.20: Current test is ./cyoa-step1 test/step4_test1 < /dev/null
-----------------------------
Your output looks good. Lets check valgrind
Valgrind was clean


1.21: Current test is ./cyoa-step1 test/step4_test2 < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Invalid digits from story.txt for page 

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


1.22: Current test is ./cyoa-step1 test/step4_test3 < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Story.txt format for variable incorrect

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


1.23: Current test is ./cyoa-step1 test/step4_test4 < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Invalid digits from story.txt for value 

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


1.24: Current test is ./cyoa-step1 test/step4_test5 < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Out of range error

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


1.25: Current test is ./cyoa-step1 test/step3_test1 < /dev/null
-----------------------------
Your output looks good. Lets check valgrind
Valgrind was clean


1.26: Current test is ./cyoa-step1 test/step3_test2 < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Declaration order incorrect

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


1.27: Current test is ./cyoa-step1 test/step3_test3 < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Declaration order incorrect

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


1.28: Current test is ./cyoa-step1 test/step3_test4 < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Declaration order incorrect

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


1.29: Current test is ./cyoa-step1 test/step2_test1 < /dev/null
-----------------------------
Your output looks good. Lets check valgrind
Valgrind was clean


1.30: Current test is ./cyoa-step1 test/step2_test2 < /dev/null
-----------------------------
Your output looks good. Lets check valgrind
Valgrind was clean


1.31: Current test is ./cyoa-step1 test/step2_test3 < /dev/null
-----------------------------
Your output looks good. Lets check valgrind
Valgrind was clean


1.32: Current test is ./cyoa-step1 test/step2_test4 < /dev/null
-----------------------------
Your output looks good. Lets check valgrind
Valgrind was clean


1.33: Current test is ./cyoa-step1 test/step2_test5 < /dev/null
-----------------------------
Your output looks good. Lets check valgrind
Valgrind was clean


1.34: Current test is ./cyoa-step1 test/step3_test6 < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Invalid digits from story.txt for value 

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


1.35: Current test is ./cyoa-step1 test/step3_test7 < /dev/null
-----------------------------
Your output looks good. Lets check valgrind
Valgrind was clean
No request to check for intermediate deadline completion on step 1

Step 2
Checking that cyoa-step2 compiles
rm -f *~ cyoa-step1 cyoa-step2 cyoa-step3 cyoa-step4 cyoa-step1.o cyoa-step2.o cyoa-step3.o cyoa-step4.o cyoa.o
g++    -c -o cyoa-step2.o cyoa-step2.cpp
g++ -std=gnu++11 -pedantic -Wall -Werror -ggdb3 -c cyoa.cpp
g++ -o cyoa-step2 cyoa-step2.o cyoa.o
rm cyoa.o cyoa-step2.o
The code compiled (good)
Executable cyoa-step2 exists (good)
------------------------------------
Now running YOUR tests for step 2
------------------------------------


2.1: Current test is ./cyoa-step2  < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Invalid input command

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.2: Current test is ./cyoa-step2 story1 story2 < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Invalid input command

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.3: Current test is ./cyoa-step2 story1  <  /usr/local/ece551/cyoa/story1/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Declaration order incorrect

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.4: Current test is ./cyoa-step2 story1  <  /usr/local/ece551/cyoa/story1/inputs/input1.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Declaration order incorrect

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.5: Current test is ./cyoa-step2 story1  <  /usr/local/ece551/cyoa/story1/inputs/input2.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Declaration order incorrect

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.6: Current test is ./cyoa-step2 story1  <  /usr/local/ece551/cyoa/story1/inputs/input9.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Declaration order incorrect

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.7: Current test is ./cyoa-step2 story1  <  /usr/local/ece551/cyoa/story1/inputs/input10.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Declaration order incorrect

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.8: Current test is ./cyoa-step2 test/step3_test1  <  /usr/local/ece551/cyoa/story1/inputs/input0.txt
-----------------------------
Your output looks good. Lets check valgrind
Valgrind was clean


2.9: Current test is ./cyoa-step2 story2  <  /usr/local/ece551/cyoa/story1/inputs/input9.txt
-----------------------------
Your output looks good. Lets check valgrind
Valgrind was clean


2.10: Current test is ./cyoa-step2 story2  <  /usr/local/ece551/cyoa/story1/inputs/input10.txt
-----------------------------
Your output looks good. Lets check valgrind
Valgrind was clean


2.11: Current test is ./cyoa-step2 story2  <  /usr/local/ece551/cyoa/story1/inputs/input12.txt
-----------------------------
Your output looks good. Lets check valgrind
Valgrind was clean


2.12: Current test is ./cyoa-step2 story1  <  nothing
-----------------------------
You considered this a failure case:
/dev/fd/3: line 528: nothing: No such file or directory
But we did not.


2.13: Current test is ./cyoa-step2 story3  <  /usr/local/ece551/cyoa/story3/inputs/input15.txt
-----------------------------
Your output looks good. Lets check valgrind
Valgrind was clean


2.14: Current test is ./cyoa-step2 story3  <  /usr/local/ece551/cyoa/story3/inputs/input16.txt
-----------------------------
Your output looks good. Lets check valgrind
Valgrind was clean


2.15: Current test is ./cyoa-step2 story3  <  /usr/local/ece551/cyoa/story3/inputs/input17.txt
-----------------------------
Your output looks good. Lets check valgrind
Valgrind was clean


2.16: Current test is ./cyoa-step2 story3  <  /usr/local/ece551/cyoa/story3/inputs/input18.txt
-----------------------------
Your output looks good. Lets check valgrind
Valgrind was clean


2.17: Current test is ./cyoa-step2 story3  <  /usr/local/ece551/cyoa/story3/inputs/input19.txt
-----------------------------
Your output looks good. Lets check valgrind
Valgrind was clean


2.18: Current test is ./cyoa-step2 story3  <  /usr/local/ece551/cyoa/story2/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Input is not good

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.19: Current test is ./cyoa-step2 story3  <  /usr/local/ece551/cyoa/story1/inputs/input1.txt
-----------------------------
Your output looks good. Lets check valgrind
Valgrind was clean


2.20: Current test is ./cyoa-step2 test/step4_test3  <  /usr/local/ece551/cyoa/story3/inputs/input1.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Story.txt format for variable incorrect

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.21: Current test is ./cyoa-step2 test/step4_test3  <  /usr/local/ece551/cyoa/story3/inputs/input2.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Story.txt format for variable incorrect

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.22: Current test is ./cyoa-step2 test/step4_test4  <  /usr/local/ece551/cyoa/story3/inputs/input3.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Invalid digits from story.txt for value 

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.23: Current test is ./cyoa-step2 test/step4_test3  <  /usr/local/ece551/cyoa/story3/inputs/input4.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Story.txt format for variable incorrect

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.24: Current test is ./cyoa-step2 test/step4_test5  <  /usr/local/ece551/cyoa/story3/inputs/input5.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Out of range error

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.25: Current test is ./cyoa-step2 test/step4_test3  <  /usr/local/ece551/cyoa/story3/inputs/input6.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Story.txt format for variable incorrect

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.26: Current test is ./cyoa-step2 test/step4_test5  <  /usr/local/ece551/cyoa/story3/inputs/input7.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Out of range error

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.27: Current test is ./cyoa-step2 test/step4_test4  <  /usr/local/ece551/cyoa/story3/inputs/input8.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Invalid digits from story.txt for value 

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.28: Current test is ./cyoa-step2 test/step3_test4  <  /usr/local/ece551/cyoa/story3/inputs/input5.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Declaration order incorrect

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.29: Current test is ./cyoa-step2 test/step2_test1  <  /usr/local/ece551/cyoa/story3/inputs/input5.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The story does not have a Lose page

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.30: Current test is ./cyoa-step2 test/step2_test2  <  /usr/local/ece551/cyoa/story3/inputs/input5.txt
-----------------------------
Your output looks good. Lets check valgrind
Valgrind was clean


2.31: Current test is ./cyoa-step2 test/step3_test6  <  /usr/local/ece551/cyoa/story3/inputs/input5.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Invalid digits from story.txt for value 

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.32: Current test is ./cyoa-step2 test/step3_test6  <  /usr/local/ece551/cyoa/story3/inputs/input5.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Invalid digits from story.txt for value 

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.33: Current test is ./cyoa-step2 test/step3_test6  <  /usr/local/ece551/cyoa/story3/inputs/input5.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Invalid digits from story.txt for value 

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean
No request to check for intermediate deadline completion on step 2

Step 3
Checking that cyoa-step3 compiles
rm -f *~ cyoa-step1 cyoa-step2 cyoa-step3 cyoa-step4 cyoa-step1.o cyoa-step2.o cyoa-step3.o cyoa-step4.o cyoa.o
g++    -c -o cyoa-step3.o cyoa-step3.cpp
g++ -std=gnu++11 -pedantic -Wall -Werror -ggdb3 -c cyoa.cpp
g++ -o cyoa-step3 cyoa-step3.o cyoa.o
rm cyoa.o cyoa-step3.o
The code compiled (good)
Executable cyoa-step3 exists (good)
------------------------------------
Now running YOUR tests for step 3
------------------------------------


3.1: Current test is ./cyoa-step3 story1 < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Declaration order incorrect

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


3.2: Current test is ./cyoa-step3 story2 < /dev/null
-----------------------------
Your output looks good. Lets check valgrind
Valgrind was clean


3.3: Current test is ./cyoa-step3 story1 story2 < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Invalid input command

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


3.4: Current test is ./cyoa-step3  < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Invalid input command

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


3.5: Current test is ./cyoa-step3 test/NoDelimiter < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Invalid digits from story.txt for page 

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


3.6: Current test is ./cyoa-step3 test/no_story < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Fail to open story.txt file

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


3.7: Current test is ./cyoa-step3 test/pageDeclareOrder < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Declaration order incorrect

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


3.8: Current test is ./cyoa-step3 test/size_t_2 < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Invalid digits from story.txt for page 

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


3.9: Current test is ./cyoa-step3 test/step3_test6 < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Invalid digits from story.txt for value 

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean
No request to check for intermediate deadline completion on step 3

Step 4
Checking that cyoa-step4 compiles
rm -f *~ cyoa-step1 cyoa-step2 cyoa-step3 cyoa-step4 cyoa-step1.o cyoa-step2.o cyoa-step3.o cyoa-step4.o cyoa.o
g++    -c -o cyoa-step4.o cyoa-step4.cpp
g++ -std=gnu++11 -pedantic -Wall -Werror -ggdb3 -c cyoa.cpp
g++ -o cyoa-step4 cyoa-step4.o cyoa.o
rm cyoa-step4.o cyoa.o
The code compiled (good)
Executable cyoa-step4 exists (good)
------------------------------------
Now running YOUR tests for step 4
------------------------------------


4.1: Current test is ./cyoa-step4 test/step4_test6  <  /usr/local/ece551/cyoa/story3/inputs/input7.txt
-----------------------------
You considered this a failure case:
Invalid digits from story.txt for page 

But we did not.


4.2: Current test is ./cyoa-step4 test/step4_test6  <  /usr/local/ece551/cyoa/story3/inputs/input8.txt
-----------------------------
You considered this a failure case:
Invalid digits from story.txt for page 

But we did not.


4.3: Current test is ./cyoa-step4 test/step4_test6  <  /usr/local/ece551/cyoa/story3/inputs/input15.txt
-----------------------------
You considered this a failure case:
Invalid digits from story.txt for page 

But we did not.


4.4: Current test is ./cyoa-step4 test/step4_test6  <  /usr/local/ece551/cyoa/story3/inputs/input16.txt
-----------------------------
You considered this a failure case:
Invalid digits from story.txt for page 

But we did not.


4.5: Current test is ./cyoa-step4 test/step4_test6  <  /usr/local/ece551/cyoa/story3/inputs/input17.txt
-----------------------------
You considered this a failure case:
Invalid digits from story.txt for page 

But we did not.


4.6: Current test is ./cyoa-step4 test/step3_test6  <  /usr/local/ece551/cyoa/story3/inputs/input18.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Invalid digits from story.txt for value 

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


4.7: Current test is ./cyoa-step4 test/step3_test6  <  /usr/local/ece551/cyoa/story3/inputs/input19.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Invalid digits from story.txt for value 

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


4.8: Current test is ./cyoa-step4 test/step3_test6  <  /usr/local/ece551/cyoa/story2/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Invalid digits from story.txt for value 

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


4.9: Current test is ./cyoa-step4 test/step3_test6  <  story1/inputs/input1.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Invalid digits from story.txt for value 

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


4.10: Current test is ./cyoa-step4 story3  <  story1/inputs/input1.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Input is not good

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


4.11: Current test is ./cyoa-step4 story3  < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Input is not good

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


4.12: Current test is ./cyoa-step4 story3 < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
Input is not good

-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean
No request to check for intermediate deadline completion on step 4

You have NOT passed your test cases!
You should go and figure out/understand where thing went wrong
And fix the problem(s) before the deadline

Overall Grade: NO GRADE YET
